helm_configuration:
  frequency: 10.0

finite_state_machine:
  - name: start
    mode: idle
    initial: true
    transitions:
      - hdepth
      - evaluation
      - kill

  - name: dive
    mode: goto_depth
    transitions:
      - start
      - dive
      - kill

  - name: kill
    mode: idle
    transition:
      - start

  - name: evaluation
    mode: idle
    transitions:
      - start
      - kill

behaviors:
  - name: motion_evaluation
    plugin: helm::MotionEvaluation
    states:
      - { name: evaluation, priority: 1}

  - name: depth_tracking
    plugin: helm::DepthTracking
    states:
      - { name: dive, priority: 1 }

  - name: periodic_sufacing
    plugin: helm::PeriodicSurface
    states:
      - {name: dive, priority: 2 }
